export { default as Sidebar } from "./sideBar/sideBar";
export { default as AreaCards } from "./dashboard/areaCards/areaCards";
export { default as AreaCharts } from "./dashboard/areaCharts/areaCharts";
export { default as AreaTop } from "./dashboard/areaTop/areaTop";
export { default as AreaLineChart } from "./dashboard/areaCharts/AreaLineChart";
export { default as Vendedores } from "./pages/tabelas/vendedoresScreen";
export { default as Vendas } from "./pages/tabelas/vendasScreen";
export { default as Clientes } from "./pages/tabelas/clientesScreen";
export { default as Comissao } from "./pages/tabelas/comissaoScreen";
export { default as Produtos } from "./pages/tabelas/produtosScreen";
export { default as Login} from "./pages/login/Login";
export { default as Cadastro} from "./pages/cadastro/Cadastro";